### ISSUE TITLE
Unsupported hash MD4 - NoneType object has no attribute split

### ISSUE THREAD

**Issue by mlinton** [garrettfoster13/sccmhunter#38]
Looks like there is a dependency on an older python module that supports MD4, while the version I'm using does not.

Installed requests_ntlm==1.2.0 and now that works but getting a 'NoneType' object when attempting to extract policies with the http module.

![image](https://github.com/garrettfoster13/sccmhunter/assets/2158650/462e340d-617b-4743-9923-19d8c0e80dfb)

Now with the updated requests_ntlm library

![image](https://github.com/garrettfoster13/sccmhunter/assets/2158650/438bd592-6d43-4c41-aa63-4e32a5e99e96)

**Comment by mlinton** [comment]
I'm using a venv environment as well so the libraries should all be exactly as defined.

**Comment by garrettfoster13** [comment]
Thanks for creating the issue @mlinton. Looks like following the library update, the error that's coming back wasn't properly handled when there's an empty response from the web server. I'll have to test this, but my assumption here is the hard coded 10 second sleep time to request the config isn't long enough. What I could do is provide a few options.

1. Add a flag to specify the sleep time -- this could fix it but could also be problematic if the sleep time given still isn't enough
2. Each request has a UUID so I could have the tool send that to stdout so you can manually request the config at a later time
3. `-debug` could also print the web server response to stdout if that would be useful

This error is hard to track down because of different configurations. Let me know your thoughts

**Comment by mlinton** [comment]
After looking into this further it looks like an issue with Python 3.11 and not supporting the older MD4 hash-type, just trying to figure out how to fix it.

**Comment by gladiatx0r** [comment]
I was able to resolve the 'unsupported hash type md4' error by updating my openssl configuration to enable the legacy provider, enabling support for md4.

Modify /etc/ssl/openssl.cnf to 're-enable' md4.

> [provider_sect]
> default = default_sect
> legacy = legacy_sect
> 
> [default_sect]
> activate = 1
> 
> [legacy_sect]
> activate = 1

Solution courtesy of [SO](https://stackoverflow.com/a/72807264/534062).
